import { describe, it, expect } from "vitest";
import {
  existsSync,
  mkdtempSync,
  readFileSync,
  rmSync,
  writeFileSync,
  mkdirSync,
} from "node:fs";
import { execSync, spawnSync } from "node:child_process";
import { join } from "node:path";
import { tmpdir } from "node:os";
import { parse, renderRust } from "../src/index.js";

/**
 * Regression test: every canonical .onto in `examples/` must produce
 * Rust that passes `cargo check` cleanly (warnings allowed, errors
 * are not).
 *
 * Why this exists: phase15.*.test.ts files verify codegen by regex on
 * the emitted source — they catch shape regressions but missed a real
 * type-mismatch bug (S31): the OCL invariant `self.<idProp> <> null`
 * emitted `self.<idProp> != None`, which fails rustc because the
 * field is a branded newtype, not `Option<…>`. Now `validators.ts`
 * elides the redundant check; this test guarantees nothing similar
 * slips through again.
 *
 * If `cargo` is not on PATH (CI without Rust), all tests in this
 * suite are skipped — they're a quality-gate, not a build dep.
 *
 * We only test the `alloc` target. The `no-alloc` target depends on
 * the `heapless` crate which requires a working MSVC/MinGW linker
 * for its build script. CI containers without that toolchain would
 * spuriously fail. Once `no-alloc` is type-correct (same codegen
 * path), checking `alloc` is sufficient evidence.
 */

function cargoAvailable(): boolean {
  const r = spawnSync("cargo", ["--version"], { stdio: "ignore" });
  return r.status === 0;
}

const examples = [
  "lpf.onto",
  "drone.onto",
  "ardupilot_lowpass.onto",
  "ardupilot_ac_pid.onto",
  // Phase 16+ migrations (DerivativeFilter, AP_Math, AP_Motors,
  // AP_AHRS, AP_Fence) — drive a real ArduPilot flight stack
  // through the new contract surface (effects, return types,
  // internal/default properties, Option<T>).
  "ardupilot_derivative.onto",
  "ardupilot_math.onto",
  "ardupilot_motors.onto",
  "ardupilot_ahrs.onto",
  "ardupilot_fence.onto",
  // AP_NavEKF3 — Kalman filter state. Stress test for Set<Real>
  // (covariance diagonals) + many isFinite()/post-conditions.
  // Generated 2026-05-20 by Flash 2.5 via the dashboard pipeline;
  // first run that exercised Set<Copy>->forAll which surfaced
  // (and fixed) the iter() / iter().copied() bug.
  "ardupilot_navekf3.onto",
  // Phase 16.5 — Array<T, N> + nested Array<Array<…>> primitives.
  // Pins the Array-shaped state-vector pattern so the few-shot
  // corpus example stays compile-clean.
  "array_state_vector.onto",
  // AP_GPS frontend — added 2026-05-20 from the second batch
  // migration run (cleanest first-shot convergence: 1 iter, 22s).
  "ardupilot_gps.onto",
  // AP_Baro / AP_RangeFinder — generated by Flash 2.5, originally
  // broke cargo check on the lambda-body null-elision bug and on
  // hard-coded String identity. Both fixed; .onto sources unchanged
  // from the Flash output, only ontodls codegen changed.
  "ardupilot_baro.onto",
  "ardupilot_rangefinder.onto",
  // AP_BattMonitor — unblocked 2026-05-20 by switching Set<NamedType>
  // to Vec<T> (structs aren't Ord so they can't be BTreeSet elements).
  // Exercises Set<NamedType> with `->includes(struct)` membership.
  "ardupilot_battmonitor.onto",
];

/**
 * Previously-broken examples that now compile. Kept as a note so a
 * future regression author can grep for it:
 *   drone.onto — fixed 2026-05-22 by Bug A (lambda-variable type
 *   tracking in codegen-rust/eventWrappers + validators) and Bug B
 *   (param move-vs-borrow: clone non-Copy params before impl_fn if
 *   referenced in posts).
 */

const HAS_CARGO = cargoAvailable();

describe.skipIf(!HAS_CARGO)(
  "codegen-rust — generated crates compile (cargo check, alloc target)",
  () => {
    for (const example of examples) {
      it(`${example} → compiles cleanly`, () => {
        const examplePath = join(process.cwd(), "examples", example);
        if (!existsSync(examplePath)) {
          throw new Error(
            `example not found: ${examplePath} — keep this list in sync with examples/`,
          );
        }
        const source = readFileSync(examplePath, "utf8");
        const { ast, errors } = parse(source);
        if (errors.length > 0) {
          throw new Error(
            `parse/semantic errors in ${example}:\n` +
              errors.map((e) => `  ${e.code ?? e.stage}: ${e.message}`).join("\n"),
          );
        }
        const crateName = example
          .replace(/\.onto$/, "")
          .replace(/[^A-Za-z0-9_]/g, "_");
        const { cargoToml, libRs } = renderRust(ast!, { crateName });
        const dir = mkdtempSync(join(tmpdir(), `ontodls_compile_${crateName}_`));
        try {
          writeFileSync(join(dir, "Cargo.toml"), cargoToml, "utf8");
          mkdirSync(join(dir, "src"), { recursive: true });
          writeFileSync(join(dir, "src", "lib.rs"), libRs, "utf8");
          // cargo check: type-checks without producing an executable.
          // Pipe stderr+stdout so the assertion message has the real
          // rustc diagnostics if it fails.
          let result;
          try {
            result = execSync("cargo check --lib --message-format=short", {
              cwd: dir,
              stdio: ["ignore", "pipe", "pipe"],
              encoding: "utf8",
            });
          } catch (err: any) {
            throw new Error(
              `cargo check FAILED for ${example}\n\n` +
                `crate dir: ${dir}\n\n` +
                `stdout:\n${err.stdout ?? ""}\n\n` +
                `stderr:\n${err.stderr ?? ""}`,
            );
          }
          // Sanity: cargo check exit 0 + no "error[" lines in stderr.
          expect(result).not.toMatch(/^error(\[|:)/m);
        } finally {
          rmSync(dir, { recursive: true, force: true });
        }
      }, 120_000);
    }

    // Regression: Set<Copy> forAll/exists in an invariant must emit
    // `.iter().copied()` so the lambda binds `T` (not `&T`). Before
    // the fix the codegen produced `set.iter().all(|__x| __x >= 0.0)`,
    // which rustc rejected with `expected &f64, found f64` because
    // `BTreeSet<f64>::iter()` yields `&f64`. Caught live during EKF
    // codegen; this test pins the fix.
    const setCopyInvariantSource = `schema "onto/0.1";
namespace set_copy_test;

kind Sensor {
  identity: id;
  property id: String;
  property diagonals: Set<Real>;
  property ticks: Set<Integer>;
  invariants {
    self.diagonals->forAll(d | d >= 0.0);
    self.ticks->exists(t | t > 0);
  }
}
`;
    it("Set<Copy> forAll/exists in invariants → compiles cleanly", () => {
      const { ast, errors } = parse(setCopyInvariantSource);
      if (errors.length > 0) {
        throw new Error(
          `parse/semantic errors:\n` +
            errors.map((e) => `  ${e.code ?? e.stage}: ${e.message}`).join("\n"),
        );
      }
      const crateName = "set_copy_invariant_regression";
      const { cargoToml, libRs } = renderRust(ast!, { crateName });
      // Sanity-check the emitted source has the .copied() adapter
      // before we even hand it to cargo — a faster failure mode for
      // shape regressions.
      expect(libRs).toMatch(/\.iter\(\)\.copied\(\)\.(all|any)\(/);
      const dir = mkdtempSync(join(tmpdir(), `ontodls_compile_${crateName}_`));
      try {
        writeFileSync(join(dir, "Cargo.toml"), cargoToml, "utf8");
        mkdirSync(join(dir, "src"), { recursive: true });
        writeFileSync(join(dir, "src", "lib.rs"), libRs, "utf8");
        let result;
        try {
          result = execSync("cargo check --lib --message-format=short", {
            cwd: dir,
            stdio: ["ignore", "pipe", "pipe"],
            encoding: "utf8",
          });
        } catch (err: any) {
          throw new Error(
            `cargo check FAILED for Set<Copy> regression\n\n` +
              `crate dir: ${dir}\n\n` +
              `stdout:\n${err.stdout ?? ""}\n\n` +
              `stderr:\n${err.stderr ?? ""}`,
          );
        }
        expect(result).not.toMatch(/^error(\[|:)/m);
      } finally {
        rmSync(dir, { recursive: true, force: true });
      }
    }, 120_000);
  },
);
