/**
 * Phase 15 / 15.7 — Rust codegen entry point.
 *
 * `renderRust(ast, options)` returns { cargoToml, libRs }.
 *
 * Two targets:
 *   - "alloc" (default): uses `alloc::*` types. Needs a global allocator
 *     (embedded-alloc, esp-alloc, or std on hosted).
 *   - "no-alloc": uses `heapless::*` with fixed capacities. No allocator
 *     required. Cargo.toml depends on `heapless`.
 */

import type { OntoFile } from "../ast/index.js";
import { renderRustTypes } from "./types.js";
import { renderRustFactories } from "./factories.js";
import { renderRustValidators } from "./validators.js";
import { renderRustEventWrappers } from "./eventWrappers.js";
import { renderRustCommitmentRegistries } from "./commitmentRegistries.js";
import { renderRustProptests, type RenderProptestsResult } from "./proptests.js";
import {
  type RustFloat,
  type RustTarget,
  type RustTargetConfig,
  DEFAULT_CAPACITY,
  DEFAULT_FLOAT,
} from "./typeMapping.js";

export interface RenderRustOptions {
  readonly crateName?: string;
  readonly crateVersion?: string;
  /** "alloc" (default) or "no-alloc". */
  readonly target?: RustTarget;
  /** Capacity for heapless containers in no-alloc mode. Default 16. */
  readonly heaplessCapacity?: number;
  /** Phase 15.8: emit `<event>_wrapped_async` variants. Default false. */
  readonly emitAsync?: boolean;
  /**
   * Float precision for OCL Real. Defaults to "f64". Use "f32" for
   * embedded targets without double-precision FPU (Cortex-M0/M3, etc.).
   */
  readonly float?: RustFloat;
}

export interface RenderRustOutput {
  readonly cargoToml: string;
  readonly libRs: string;
}

export function renderRust(
  file: OntoFile,
  options: RenderRustOptions = {},
): RenderRustOutput {
  const crateName = options.crateName ?? "ontodsl_generated";
  const crateVersion = options.crateVersion ?? "0.1.0";
  const cfg: RustTargetConfig = {
    target: options.target ?? "alloc",
    capacity: options.heaplessCapacity ?? DEFAULT_CAPACITY,
    emitAsync: options.emitAsync ?? false,
    float: options.float ?? DEFAULT_FLOAT,
  };

  const cargoToml = renderCargoToml(crateName, crateVersion, cfg);
  const libRs = renderLibRs(file, cfg);
  return { cargoToml, libRs };
}

function renderCargoToml(name: string, version: string, cfg: RustTargetConfig): string {
  const deps = cfg.target === "no-alloc"
    ? `heapless = "0.8"`
    : `# No runtime deps — generated code uses only core + alloc.`;
  return [
    `[package]`,
    `name = "${name}"`,
    `version = "${version}"`,
    `edition = "2021"`,
    `description = "Generated by Onto DSL — do not edit manually."`,
    ``,
    `[lib]`,
    `crate-type = ["rlib"]`,
    ``,
    `[dependencies]`,
    deps,
    ``,
  ].join("\n");
}

function renderLibRs(file: OntoFile, cfg: RustTargetConfig): string {
  const parts: string[] = [];

  parts.push(`// ═══════════════════════════════════════════════════════════════════`);
  parts.push(`// AUTO-GENERATED from Onto DSL. Do not edit.`);
  parts.push(`// Target: ${cfg.target}${cfg.target === "no-alloc" ? ` (capacity=${cfg.capacity})` : ""}; Real → ${cfg.float}.`);
  parts.push(`// ═══════════════════════════════════════════════════════════════════`);
  parts.push(``);
  parts.push(`#![no_std]`);
  parts.push(``);

  if (cfg.target === "alloc") {
    parts.push(`// alloc target: String/BTreeSet/Vec/BTreeMap from alloc.`);
    parts.push(`extern crate alloc;`);
  } else {
    parts.push(`// no-alloc target: heapless containers with fixed capacity ${cfg.capacity}.`);
    parts.push(`// No global allocator required.`);
  }
  parts.push(``);
  parts.push(renderRustTypes(file, cfg));
  parts.push(``);
  parts.push(renderRustFactories(file, cfg));
  parts.push(``);
  parts.push(renderRustValidators(file, cfg));
  parts.push(``);
  parts.push(renderRustEventWrappers(file, cfg));
  parts.push(``);
  parts.push(renderRustCommitmentRegistries(file, cfg));
  parts.push(``);

  return parts.join("\n");
}

/**
 * Phase Q3 / Paso 1 — generate property-based tests from the OCL
 * invariants + event pre-conditions. Returns the test module text
 * and the count of emitted tests. Caller decides whether to write
 * the file alongside `lib.rs` and add `proptest` as a dev-dep.
 */
export function renderRustProptestsForFile(
  file: OntoFile,
  options: RenderRustOptions = {},
): RenderProptestsResult {
  const cfg: RustTargetConfig = {
    target: options.target ?? "alloc",
    capacity: options.heaplessCapacity ?? DEFAULT_CAPACITY,
    emitAsync: options.emitAsync ?? false,
    float: options.float ?? DEFAULT_FLOAT,
  };
  return renderRustProptests(file, cfg);
}

export {
  renderRustTypes,
  renderRustFactories,
  renderRustValidators,
  renderRustEventWrappers,
  renderRustCommitmentRegistries,
};
