// C:\Users\Rene Meza\.gemini\antigravity-ide\brain\abce5c13-68fd-4164-9336-10f9fe6b3d4b/scratch/migrate_drone.js

const apiBase = "http://localhost:3000";
const apiKey = "AIzaSyComMIv5Br1Hum9MvOpqiA_XeGCC80HoAk";

async function delay(ms) {
  return new Promise(resolve => setTimeout(resolve, ms));
}

async function getState() {
  const response = await fetch(`${apiBase}/api/migrate/state`);
  return response.json();
}

async function resetProject(project = "drone-delivery") {
  console.log(`[DroneMigrate] Resetting project to: ${project}...`);
  const response = await fetch(`${apiBase}/api/migrate/reset-project`, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ project })
  });
  return response.json();
}

async function initializeRoadmap(project = "drone-delivery") {
  console.log(`[DroneMigrate] Initializing system and parsing OntoUML model...`);
  const response = await fetch(`${apiBase}/api/migrate/initialize-roadmap`, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ project })
  });
  return response.json();
}

async function startStep(target = "rust") {
  console.log(`[DroneMigrate] Starting step migration...`);
  const response = await fetch(`${apiBase}/api/migrate/start-step`, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      "X-Gemini-API-Key": apiKey
    },
    body: JSON.stringify({
      model: "gemini-2.5-flash",
      target: target
    })
  });
  return response.json();
}

async function approveStep() {
  console.log(`[DroneMigrate] Approving step...`);
  const response = await fetch(`${apiBase}/api/migrate/approve`, {
    method: "POST"
  });
  return response.json();
}

async function run() {
  console.log("=== STARTING DRONE DELIVERY MIGRATION WITH GEMINI 2.5 FLASH ===");

  // 1. Reset project workspace to drone-delivery
  await resetProject("drone-delivery");
  await delay(1000);

  // 2. Initialize project (Step 0)
  await initializeRoadmap("drone-delivery");
  await delay(1500);

  let state = await getState();
  console.log(`[Initialize] Status: ${state.status}, Active Step: ${state.activeStepIndex}, Nodes: ${state.nodesCount}, Edges: ${state.edgesCount}`);

  if (state.activeStepIndex !== 1) {
    console.error("Failed to initialize active step to 1.");
    process.exit(1);
  }

  // 3. Sequentially migrate steps 1 to 5
  for (let stepIdx = 1; stepIdx <= 5; stepIdx++) {
    console.log(`\n---------------------------------------------`);
    console.log(`>>> STARTING STEP ${stepIdx}: ${state.projectRoadmap[stepIdx].name} <<<`);
    console.log(`---------------------------------------------`);

    // Start migration of current step
    await startStep("rust");

    // Wait until state goes to paused_awaiting_approval
    while (true) {
      state = await getState();
      console.log(`[Poll] Status: ${state.status}, Active Step: ${state.activeStepIndex}`);
      if (state.status === "paused_awaiting_approval") {
        console.log(`\n⚠️ Z3 Hazards Audit complete for Step ${stepIdx}!`);
        console.log(JSON.stringify(state.detectedBugs, null, 2));
        console.log(`Approving Step ${stepIdx} migration...`);
        await approveStep();
        break;
      }
      if (state.status === "failed") {
        console.error(`Step ${stepIdx} failed during audit!`);
        process.exit(1);
      }
      await delay(1000);
    }

    // Wait until activeStepIndex becomes stepIdx + 1, or success if it's the last step
    while (true) {
      state = await getState();
      console.log(`[Poll] Status: ${state.status}, Active Step: ${state.activeStepIndex}`);
      
      const isCompleted = stepIdx === 5 
        ? state.status === "success" 
        : (state.activeStepIndex === stepIdx + 1 && state.status === "idle");
        
      if (isCompleted) {
        console.log(`✅ Step ${stepIdx} Completed successfully!`);
        if (state.autoGeneratedTests && state.autoGeneratedTests.length > 0) {
          console.log(`Tests generated:\n${state.autoGeneratedTests.join("\n")}`);
        }
        break;
      }
      if (state.status === "failed") {
        console.error(`Step ${stepIdx} failed during implementation / compilation!`);
        process.exit(1);
      }
      await delay(1000);
    }
  }

  console.log(`\n======================================================`);
  console.log(`🎉 DRONE DELIVERY SYSTEM SUCCESSFULLY MIGRATED AND TESTED!`);
  console.log(`======================================================`);
}

run().catch(err => {
  console.error("Error running drone migration:", err);
});
